#!/usr/bin/env bash
set -euo pipefail

DEV_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dev) DEV_MODE=true; shift ;;
    *) echo "Usage: $0 [--dev]"; exit 1 ;;
  esac
done

EPIBRIDGE_HOME="${EPIBRIDGE_HOME:-/opt/epibridge}"
REPO_URL="${REPO_URL:-https://github.com/example/epibridge.git}"
BRANCH="${BRANCH:-main}"
ENV_FILE="${EPIBRIDGE_HOME}/.env"
COMPOSE_FILE="${EPIBRIDGE_HOME}/docker-compose.yml"

echo "=== EpiBridge Install ==="

if [ "$DEV_MODE" = true ]; then
  if [ ! -d "$EPIBRIDGE_HOME" ]; then
    echo "ERROR: $EPIBRIDGE_HOME does not exist."
    echo "In --dev mode the source tree must be mounted or symlinked before running install.sh."
    exit 1
  fi
else
  if [ ! -d "$EPIBRIDGE_HOME" ]; then
    echo "Creating $EPIBRIDGE_HOME"
    mkdir -p "$EPIBRIDGE_HOME"
  fi

  # Clone or update repository
  if [ -d "$EPIBRIDGE_HOME/.git" ]; then
    echo "Updating repository..."
    cd "$EPIBRIDGE_HOME"
    git fetch origin
    git checkout "$BRANCH"
    git pull origin "$BRANCH"
  else
    echo "Cloning repository..."
    git clone --branch "$BRANCH" "$REPO_URL" "$EPIBRIDGE_HOME"
  fi
fi

cd "$EPIBRIDGE_HOME"

# Generate .env if not present
if [ ! -f "$ENV_FILE" ]; then
  echo "Generating .env..."
  POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')
  SECRET_KEY=$(openssl rand -base64 64 | tr -d '\n')
  REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')

  cat > "$ENV_FILE" <<EOF
# EpiBridge - generated by install.sh
POSTGRES_DB=epibridge
POSTGRES_USER=epibridge
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_HOST=redis
REDIS_PORT=6379

SECRET_KEY=${SECRET_KEY}
FIREBASE_PROJECT_ID=
FIREBASE_PRIVATE_KEY_ID=
FIREBASE_PRIVATE_KEY=
FIREBASE_CLIENT_EMAIL=
FIREBASE_CLIENT_ID=

DOMAIN=localhost
ADMIN_EMAIL=admin@epibridge.local
EOF

  chmod 600 "$ENV_FILE"
  echo ".env created at $ENV_FILE"
  if [ "$DEV_MODE" = true ]; then
    echo "Using generated defaults for development."
  else
    echo "Edit $ENV_FILE to configure Firebase and domain before continuing."
    echo "Then re-run install.sh to proceed."
    exit 0
  fi
fi

# Build and start services
echo "Building and starting Docker services..."
docker compose -f "$COMPOSE_FILE" build
docker compose -f "$COMPOSE_FILE" up -d

# Wait for database
echo "Waiting for PostgreSQL..."
until docker compose -f "$COMPOSE_FILE" exec -T postgres pg_isready -U epibridge 2>/dev/null; do
  sleep 2
done
echo "PostgreSQL is ready."

# Run migrations
echo "Running database migrations..."
docker compose -f "$COMPOSE_FILE" exec -T backend alembic upgrade head

# Seed admin account
echo "Seeding administrator account..."
docker compose -f "$COMPOSE_FILE" exec -T backend python -m app.cli seed-admin

# Health check
echo "Running health checks..."
./scripts/healthcheck.sh

echo ""
echo "=== EpiBridge installation complete ==="
echo "Frontend: https://$(grep ^DOMAIN "$ENV_FILE" | cut -d= -f2)/"
echo "API:      https://$(grep ^DOMAIN "$ENV_FILE" | cut -d= -f2)/api/health"
